### ISSUE TITLE
Relies on out of Service .Net Version

### ISSUE THREAD

**Issue by rtmann** [KhaosCoders/dotnet-project-graph#1]
This should work on .net 8, anyway to update the dependencies to be less restrictive?

**Comment by Khaos66** [comment]
Hi! I'll take a look

**Comment by Khaos66** [comment]
I just pushed version `1.1.0` to nuget.org
It need to pass some checks by nuget and will be available soon
https://www.nuget.org/packages/Project.Graph.Tool#versions-body-tab
